version: 2
updates:
- package-ecosystem: pip
  directory: "/requirements"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  reviewers:
  - sarah-clements
  labels:
  - dependencies
  - python
  allow:
  - dependency-name: django
